"""Generate TFT_eSPI smooth-font (.vlw) C arrays from open-source TTFs.

Usage:  python tools/gen_fonts.py
Needs:  Pillow (pip install pillow)

Downloads Inter and JetBrains Mono (SIL OFL 1.1) into tools/.cache and writes
one header per font into include/fonts/. Edit FONTS below to change the set.
"""

import os
import urllib.request

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "tools", ".cache")
OUT = os.path.join(ROOT, "include", "fonts")

SOURCES = {
    "Inter": "https://github.com/google/fonts/raw/main/ofl/inter/Inter%5Bopsz,wght%5D.ttf",
    "JetBrainsMono": "https://github.com/google/fonts/raw/main/ofl/jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf",
}

# (C symbol, family, pixel size, weight)
FONTS = [
    ("FontUiSm",   "Inter",         13, 600),
    ("FontUiMd",   "Inter",         16, 600),
    ("FontUiLg",   "Inter",         22, 700),
    ("FontUiXl",   "Inter",         28, 700),
    ("FontMonoSm", "JetBrainsMono", 13, 500),
    ("FontMonoMd", "JetBrainsMono", 16, 600),
]

# Printable ASCII plus a few UI symbols.
CHARS = [chr(c) for c in range(0x20, 0x7F)] + ["·", "°", "…", "•"]


def fetch(family):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, family + ".ttf")
    if not os.path.exists(path):
        print("downloading", family)
        urllib.request.urlretrieve(SOURCES[family], path)
    return path


def load(family, size, weight):
    font = ImageFont.truetype(fetch(family), size)
    axes = []
    for axis in font.get_variation_axes():
        name = axis["name"].decode() if isinstance(axis["name"], bytes) else axis["name"]
        if name == "Weight":
            axes.append(weight)
        elif name == "Optical size":
            axes.append(max(axis["minimum"], min(axis["maximum"], size)))
        else:
            axes.append(axis["default"])
    font.set_variation_by_axes(axes)
    return font


def render(font, size):
    glyphs = []
    canvas = size * 3
    base = size * 2
    for ch in sorted(CHARS, key=ord):
        img = Image.new("L", (canvas, canvas), 0)
        ImageDraw.Draw(img).text((size, base), ch, font=font, fill=255, anchor="ls")
        advance = round(font.getlength(ch))
        box = img.getbbox()
        if box is None:  # whitespace
            glyphs.append((ord(ch), 0, 0, advance, 0, 0, b""))
            continue
        x0, y0, x1, y1 = box
        bitmap = img.crop(box).tobytes()
        glyphs.append((ord(ch), y1 - y0, x1 - x0, advance, base - y0, x0 - size, bitmap))
    return glyphs


def vlw(glyphs, size):
    def i32(v):
        return (v & 0xFFFFFFFF).to_bytes(4, "big")

    ascent = max(g[4] for g in glyphs)
    descent = max(g[1] - g[4] for g in glyphs)
    data = bytearray()
    for v in (len(glyphs), 11, size, 0, ascent, descent):
        data += i32(v)
    for uni, h, w, adv, dy, dx, _ in glyphs:
        for v in (uni, h, w, adv, dy, dx, 0):
            data += i32(v)
    for g in glyphs:
        data += g[6]
    return bytes(data)


def write_header(symbol, family, size, weight, data):
    path = os.path.join(OUT, symbol + ".h")
    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/gen_fonts.py - do not edit.\n")
        f.write(f"// {family} {size}px weight {weight} (SIL OFL 1.1)\n")
        f.write("#pragma once\n#include <pgmspace.h>\n\n")
        f.write(f"const uint8_t {symbol}[] PROGMEM = {{\n")
        for i in range(0, len(data), 20):
            f.write("  " + ",".join(f"0x{b:02X}" for b in data[i:i + 20]) + ",\n")
        f.write("};\n")
    print(f"{symbol:<11} {family} {size}px w{weight}: {len(data)} bytes")


def main():
    os.makedirs(OUT, exist_ok=True)
    for symbol, family, size, weight in FONTS:
        font = load(family, size, weight)
        write_header(symbol, family, size, weight, vlw(render(font, size), size))


if __name__ == "__main__":
    main()
