// Shared drawing primitives: fonts, cards, pills, buttons, icons.
// Every helper takes a TFT_eSPI& so it can draw to the panel or a sprite.
#pragma once

#include <TFT_eSPI.h>

extern TFT_eSPI tft;

// Smooth fonts (generated by tools/gen_fonts.py)
enum class Font : uint8_t { UiSm, UiMd, UiLg, UiXl, MonoSm, MonoMd };

void useFont(TFT_eSPI &g, Font font);

// Text with explicit datum and colors; returns rendered width.
int16_t text(TFT_eSPI &g, const char *s, int32_t x, int32_t y, Font font,
             uint16_t fg, uint16_t bg, uint8_t datum = TL_DATUM);

// Truncates `s` with an ellipsis so it fits in maxW pixels in `font`.
String fitText(TFT_eSPI &g, const String &s, Font font, int16_t maxW);

// Rounded card with a 1px anti-aliased border.
void card(TFT_eSPI &g, int32_t x, int32_t y, int32_t w, int32_t h, int32_t r,
          uint16_t fill, uint16_t border, uint16_t outside = 0x0000);

// Status pill: tinted fill, dot, and label. Returns pill width.
int16_t pill(TFT_eSPI &g, int32_t x, int32_t y, const char *label,
             uint16_t color, uint16_t tint, uint16_t outside = 0x0000);

// Outline button with centered label; `active` fills it with the accent.
void button(TFT_eSPI &g, int32_t x, int32_t y, int32_t w, int32_t h, const char *label,
            bool active = false);

// Wi-Fi signal bars (4 bars, `level` 0..4), bottom-left anchored at x,y.
void signalBars(TFT_eSPI &g, int32_t x, int32_t y, uint8_t level, uint16_t on, uint16_t off);

// Horizontal header rule with the brand gradient.
void headerRule(TFT_eSPI &g);

// Brand mark (24x24).
void logoMark(TFT_eSPI &g, int32_t x, int32_t y);

// Line icons drawn inside a 32x32 tinted badge at x,y.
enum class Icon : uint8_t { Power, Garage, Wifi, Pulse, Back, Plus };
void iconBadge(TFT_eSPI &g, int32_t x, int32_t y, Icon icon, uint16_t fg, uint16_t tint,
               uint16_t outside);
void iconGlyph(TFT_eSPI &g, int32_t cx, int32_t cy, Icon icon, uint16_t fg, uint16_t bg);
